# -*- coding: utf-8 -*-
"""Canva & BI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDejONKwX-ucBXluDTmn1j91p0nwi2xH
"""

import pandas as pd

df = pd.read_csv("sales_dataset.csv")

"""Explore Data"""

print(df.head())
print(df.info())
print(df.describe())

print(df.isnull().sum())

df['Profit'] = df['Profit'].fillna(df['Profit'].mean())
df['Sales'] = df['Sales'].fillna(df['Sales'].median())

df = df.drop_duplicates()

df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='%d-%m-%Y')

df['Sales'] = df['Sales'].astype(float)
df['Profit'] = df['Profit'].astype(float)
df['Quantity'] = df['Quantity'].astype(int)

df['Month'] = df['Order_Date'].dt.month
df['Year'] = df['Order_Date'].dt.year

print("Negative Sales:", (df['Sales'] < 0).sum())
print("Negative Profit:", (df['Profit'] < 0).sum())

df.to_csv("cleaned_sales_data.csv", index=False)

print("Data cleaning completed successfully!")

"""OUTLIER DETECTION"""

Q1 = df['Sales'].quantile(0.25)
Q3 = df['Sales'].quantile(0.75)
IQR = Q3 - Q1

outliers = df[(df['Sales'] < (Q1 - 1.5 * IQR)) | (df['Sales'] > (Q3 + 1.5 * IQR))]
print("Outliers detected:", len(outliers))

